name: CodeGuru Security Scan

# Triggers the workflow on pushes to any branch and on pull requests to 'main'
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  
permissions:
  contents: read
  security-events: write

jobs:
  CodeGuru-Scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Fetches all history for all branches and tags, required by CodeGuru
          fetch-depth: 0

      # Step 2: Configure AWS credentials using the secrets we stored
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # IMPORTANT: Change this to the AWS region of your S3 bucket
          aws-region: eu-west-2
      # Step 3: Run the CodeGuru Reviewer scan
      - name: Run Amazon CodeGuru Reviewer
        id: codeguru-review # Add an ID to reference the output of this step
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          # IMPORTANT: Change this to the name of the S3 bucket you created
          s3_bucket: "codeguru-reviewer-sai-groups-api"

      # Step 3: Upload results into GitHub
      - name: Upload review result
        if: ${{ github.event_name != 'push' }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeguru-results.sarif.json
          
#      # Step 4: Upload the results to GitHub's Security tab
#      - name: Upload SARIF file
#        if: success() && steps.codeguru-review.outputs.sarif_file != ''
#        uses: github/codeql-action/upload-sarif@v3
#        with:
#          # Path to the SARIF file generated by the CodeGuru action
#          sarif_file: ${{ steps.codeguru-review.outputs.sarif_file }}
#
#      # Step 5: Inform the user if no report was generated
#      - name: No report generated
#        if: success() && steps.codeguru-review.outputs.sarif_file == ''
#        run: echo "CodeGuru scan completed, but no SARIF report was generated. This is expected if no issues are found."
